name: docker image builds

on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
  checks: write
  statuses: write
jobs:
  dockerbuild:
    uses: prakashecho/docker/.github/workflows/docker.yaml@main
    #with: 
      #releaseVersion: '1'
