name: docker image builds

on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
  checks: write
  statuses: write
jobs:
  dockerbuild:
      runs-on: ubuntu-latest

      steps:
        
      - name: Install dependencies
        uses: prakashecho/docker/.github/workflows/dependency.yaml@main
        #with:
          #install-all: true  # Example: Install all dependencies
          # Alternatively, you can specify individual dependencies:
           # install-curl: true
           # install-git: true
           # install-gh: true
           # install-docker-compose: true   
         
      - name: Check versions
        run: |
          docker-compose --version
          curl --version
          git --version
          gh --version
